# este archivo va a declarar como se va a iniciar y desde donde se va a iniciar ese contenedor

services: 
  app-csv:
  # app-csv es el nombre del servicio, puede ser cualquier nombre
    build:
      context: .
      # el contexto del build es en la carpeta donde estamos ubicados
      dockerfile: Dockerfile
      # se especifica cual es el dockerfile que va a leer
    volumes:
      - .:/charts
    # se agrega volumes para que los cambios en local se muestren tambien en el contenedor